import { useParams } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { motion } from 'framer-motion';
import { Star, Users, Clock, Play, CheckCircle, BookOpen } from 'lucide-react';

// Add this type above courseDataWithAliases:
type CourseDetail = {
  title: string;
  description: string;
  instructor: string;
  instructorBio: string;
  instructorImage: string;
  rating: number;
  students: number;
  duration: string;
  level: string;
  video?: string;
  lessons: Array<{ title: string; duration: string; completed?: boolean }>;
  badge?: string;
};

const courseData: Record<string, CourseDetail> = {
  'canva': {
    title: 'How to use Canva',
    description: 'Learn the basics of creating beautiful designs with Canva. This comprehensive course will teach you everything from creating social media graphics to designing presentations and marketing materials.',
    instructor: 'Sarah Johnson',
    instructorBio: 'Former senior designer at Adobe with 10+ years teaching digital design. Sarah specializes in making complex design tools accessible to everyone.',
    instructorImage: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=200&h=200&fit=crop&crop=face',
    rating: 4.8,
    students: 1247,
    duration: '2 hours',
    level: 'Beginner',
    video: 'https://www.youtube.com/embed/5O6JKCkXg5A',
    lessons: [
      { title: 'Introduction to Canva', duration: '10 min', completed: true },
      { title: 'Creating Your First Design', duration: '15 min', completed: true },
      { title: 'Working with Templates', duration: '20 min', completed: true },
      { title: 'Adding and Editing Text', duration: '15 min', completed: true },
      { title: 'Working with Images', duration: '20 min', completed: true },
      { title: 'Using Shapes and Elements', duration: '15 min', completed: true },
      { title: 'Creating Social Media Graphics', duration: '25 min' },
      { title: 'Designing Presentations', duration: '30 min' }
    ]
  },
  'google-docs': {
    title: 'Intro to Google Docs',
    description: 'Master document creation, editing, and sharing in Google Docs. Learn to collaborate effectively and create professional documents.',
    instructor: 'Mike Chen',
    instructorBio: 'Google Workspace certified trainer helping teams work smarter. Mike has trained thousands of users in productivity tools.',
    instructorImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face',
    rating: 4.9,
    students: 2156,
    duration: '1.5 hours',
    level: 'Beginner',
    video: 'https://www.youtube.com/embed/eA2F8gBCR6E',
    lessons: [
      { title: 'Getting Started with Google Docs', duration: '10 min', completed: true },
      { title: 'Creating and Editing Documents', duration: '15 min', completed: true },
      { title: 'Formatting Text and Paragraphs', duration: '20 min', completed: true },
      { title: 'Working with Images and Tables', duration: '25 min' },
      { title: 'Sharing and Collaborating', duration: '20 min' },
      { title: 'Advanced Features', duration: '20 min' }
    ]
  },
  'digital-safety': {
    title: 'Digital Safety 101',
    description: 'Stay safe online with essential digital safety tips. Learn to protect your personal information and navigate the internet securely.',
    instructor: 'Dr. Emily Rodriguez',
    instructorBio: 'PhD in Computer Science with focus on digital safety education. Emily is passionate about making cybersecurity accessible to everyone.',
    instructorImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face',
    rating: 4.7,
    students: 892,
    duration: '3 hours',
    level: 'Beginner',
    video: 'https://www.youtube.com/embed/2x0U4F5O4uE',
    lessons: [
      { title: 'Understanding Online Threats', duration: '15 min', completed: true },
      { title: 'Creating Strong Passwords', duration: '20 min' },
      { title: 'Recognizing Phishing Attempts', duration: '25 min' },
      { title: 'Protecting Personal Information', duration: '30 min' },
      { title: 'Safe Social Media Practices', duration: '25 min' }
    ]
  },
  'quizizz': {
    title: 'Quizizz: Interactive Quizzes',
    description: 'Master Quizizz for creating, sharing, and analyzing interactive quizzes for any subject or audience.',
    instructor: 'Ana Torres',
    instructorBio: 'EdTech specialist with 7+ years helping teachers use digital tools for engagement.',
    instructorImage: 'https://randomuser.me/api/portraits/women/44.jpg',
    rating: 4.7,
    students: 180,
    duration: '2.5 hours',
    level: 'Beginner',
    badge: '/assets/courses/badges/beginner.png',
    lessons: [
      { title: '¿Qué es Quizizz!?', duration: '5 min', completed: true },
      { title: 'Primeros pasos', duration: '8 min', completed: true },
      { title: 'Crear cuenta', duration: '7 min', completed: true },
      { title: 'Iniciar sesión', duration: '5 min' },
      { title: 'Conocer el menú', duration: '10 min' },
      { title: 'Cuestionario', duration: '10 min' },
      { title: 'Crear un cuestionario', duration: '15 min' },
      { title: 'Crear pregunta', duration: '10 min' },
      { title: 'Configurar una pregunta', duration: '10 min' },
      { title: 'Ajustes de cuestionario', duration: '10 min' },
      { title: 'Agregar preguntas desde la biblioteca de Quizizz', duration: '10 min' },
      { title: 'Importar preguntas desde hoja de calculo', duration: '10 min' },
      { title: 'Guardar cuestionario', duration: '5 min' },
      { title: 'Compartir cuestionario', duration: '8 min' },
      { title: 'Compartir por dirección de correo', duration: '5 min' },
      { title: 'Compartir por link', duration: '5 min' },
      { title: 'Editar cuestionario', duration: '8 min' },
      { title: 'Jugar con cuestionario', duration: '10 min' },
      { title: 'Modos', duration: '8 min' },
      { title: 'Ajustar juego', duration: '8 min' },
      { title: 'Compartir para jugar', duration: '5 min' },
      { title: 'Vista del jugador', duration: '7 min' },
      { title: 'Vista del administrador', duration: '7 min' },
      { title: 'Revisar resultados de cuestionario', duration: '10 min' },
      { title: 'Biblioteca', duration: '8 min' },
      { title: 'Explorar', duration: '8 min' },
      { title: 'Jugar otros cuestionarios', duration: '10 min' },
      { title: 'Guardar otros cuestionarios', duration: '7 min' },
      { title: 'Compartir otros cuestionarios', duration: '7 min' },
      { title: 'Copiar y editar otros cuestionarios', duration: '7 min' },
      { title: 'Informes', duration: '10 min' },
      { title: 'Clases', duration: '8 min' },
      { title: 'Crear clases', duration: '8 min' },
      { title: 'Enlazar con Google Classroom', duration: '8 min' },
      { title: 'Ajustes de cuenta', duration: '7 min' },
    ]
  },
  'socrative': {
    title: 'Socrative: Real-Time Assessment',
    description: 'Learn to use Socrative for instant feedback, quizzes, and classroom engagement.',
    instructor: 'Luis Martínez',
    instructorBio: 'STEM educator and digital learning advocate.',
    instructorImage: 'https://randomuser.me/api/portraits/men/32.jpg',
    rating: 4.8,
    students: 150,
    duration: '2 hours',
    level: 'Intermediate',
    badge: '/assets/courses/badges/intermediate.png',
    lessons: [
      { title: '¿Qué es Socrative?', duration: '5 min', completed: true },
      { title: 'Primeros pasos', duration: '8 min', completed: true },
      { title: 'Crear cuenta', duration: '7 min', completed: true },
      { title: 'Iniciar sesión', duration: '5 min' },
      { title: 'Conocer el menú', duration: '10 min' },
      { title: 'Clases', duration: '10 min' },
      { title: 'Cambiar nombre', duration: '5 min' },
      { title: 'Compartir clase', duration: '5 min' },
      { title: 'Inicio', duration: '5 min' },
      { title: 'Respuesta múltiple', duration: '8 min' },
      { title: 'Verdadero/falso', duration: '8 min' },
      { title: 'Respuesta corta', duration: '8 min' },
      { title: 'Pruebas', duration: '10 min' },
      { title: 'Añadir pruebas', duration: '10 min' },
      { title: 'Configurar preguntas', duration: '10 min' },
      { title: 'Compartir prueba', duration: '8 min' },
      { title: 'Importar prueba de otro profesor', duration: '8 min' },
      { title: 'Importar prueba de Excel', duration: '8 min' },
      { title: 'Guardar prueba', duration: '7 min' },
      { title: 'Administrar pruebas', duration: '8 min' },
      { title: 'Eliminarlas', duration: '5 min' },
      { title: 'Copiarlas', duration: '5 min' },
      { title: 'Descargarlas', duration: '5 min' },
      { title: 'Iniciar', duration: '5 min' },
      { title: 'Iniciar pruebas', duration: '8 min' },
      { title: 'Seleccionar prueba', duration: '5 min' },
      { title: 'Métodos de entrega', duration: '8 min' },
      { title: 'Ajustes de inicio de prueba', duration: '8 min' },
      { title: 'Carrera espacial', duration: '8 min' },
      { title: 'Elegir prueba', duration: '5 min' },
      { title: 'Configurar equipos', duration: '8 min' },
      { title: 'Elegir ajustes', duration: '8 min' },
      { title: 'Pregunta final', duration: '5 min' },
      { title: 'Resultados', duration: '10 min' },
      { title: 'Compartir resultados', duration: '8 min' },
      { title: 'Exportar resultados', duration: '8 min' },
      { title: 'Informes', duration: '10 min' },
      { title: 'Buscar informes', duration: '8 min' },
      { title: 'Filtrar informes', duration: '8 min' },
      { title: 'Archivar informes', duration: '8 min' },
      { title: 'Eliminar informes', duration: '8 min' },
      { title: 'Configurar perfil', duration: '7 min' },
    ]
  },
  'brainscape': {
    title: 'Brainscape: Flashcard Mastery',
    description: 'Learn how to use Brainscape for effective learning and memorization.',
    instructor: 'Maria Garcia',
    instructorBio: 'Educational technology consultant with expertise in cognitive psychology.',
    instructorImage: 'https://randomuser.me/api/portraits/women/55.jpg',
    rating: 4.6,
    students: 120,
    duration: '1.5 hours',
    level: 'Beginner',
    badge: '/assets/courses/badges/beginner.png',
    lessons: [
      { title: '¿Qué es Brainscape?', duration: '5 min', completed: true },
      { title: 'Primeros pasos', duration: '8 min', completed: true },
      { title: 'Crear cuenta', duration: '7 min', completed: true },
      { title: 'Iniciar sesión', duration: '5 min' },
      { title: 'Conocer el menú', duration: '10 min' },
      { title: 'Clases', duration: '10 min' },
      { title: 'Cambiar nombre', duration: '5 min' },
      { title: 'Compartir clase', duration: '5 min' },
      { title: 'Inicio', duration: '5 min' },
      { title: 'Flashcards', duration: '8 min' },
      { title: 'Crear flashcard', duration: '10 min' },
      { title: 'Editar flashcard', duration: '10 min' },
      { title: 'Configurar flashcard', duration: '10 min' },
      { title: 'Compartir flashcard', duration: '8 min' },
      { title: 'Importar flashcard', duration: '8 min' },
      { title: 'Exportar flashcard', duration: '8 min' },
      { title: 'Guardar flashcard', duration: '7 min' },
      { title: 'Administrar flashcards', duration: '8 min' },
      { title: 'Eliminarlas', duration: '5 min' },
      { title: 'Copiarlas', duration: '5 min' },
      { title: 'Descargarlas', duration: '5 min' },
      { title: 'Iniciar', duration: '5 min' },
      { title: 'Iniciar sesiones', duration: '8 min' },
      { title: 'Seleccionar sesiones', duration: '5 min' },
      { title: 'Métodos de entrega', duration: '8 min' },
      { title: 'Ajustes de inicio de sesión', duration: '8 min' },
      { title: 'Carrera espacial', duration: '8 min' },
      { title: 'Elegir sesiones', duration: '5 min' },
      { title: 'Configurar equipos', duration: '8 min' },
      { title: 'Elegir ajustes', duration: '8 min' },
      { title: 'Pregunta final', duration: '5 min' },
      { title: 'Resultados', duration: '10 min' },
      { title: 'Compartir resultados', duration: '8 min' },
      { title: 'Exportar resultados', duration: '8 min' },
      { title: 'Informes', duration: '10 min' },
      { title: 'Buscar informes', duration: '8 min' },
      { title: 'Filtrar informes', duration: '8 min' },
      { title: 'Archivar informes', duration: '8 min' },
      { title: 'Eliminar informes', duration: '8 min' },
      { title: 'Configurar perfil', duration: '7 min' },
    ]
  },
  'genially': {
    title: 'Genially: Interactive Presentations',
    description: 'Learn how to create engaging and interactive presentations using Genially.',
    instructor: 'Carlos Lopez',
    instructorBio: 'Digital learning consultant with a passion for visual storytelling.',
    instructorImage: 'https://randomuser.me/api/portraits/men/66.jpg',
    rating: 4.7,
    students: 130,
    duration: '2 hours',
    level: 'Intermediate',
    badge: '/assets/courses/badges/intermediate.png',
    lessons: [
      { title: '¿Qué es Genially?', duration: '5 min', completed: true },
      { title: 'Primeros pasos', duration: '8 min', completed: true },
      { title: 'Crear cuenta', duration: '7 min', completed: true },
      { title: 'Iniciar sesión', duration: '5 min' },
      { title: 'Conocer el menú', duration: '10 min' },
      { title: 'Clases', duration: '10 min' },
      { title: 'Cambiar nombre', duration: '5 min' },
      { title: 'Compartir clase', duration: '5 min' },
      { title: 'Inicio', duration: '5 min' },
      { title: 'Presentaciones', duration: '8 min' },
      { title: 'Crear presentación', duration: '10 min' },
      { title: 'Editar presentación', duration: '10 min' },
      { title: 'Configurar presentación', duration: '10 min' },
      { title: 'Compartir presentación', duration: '8 min' },
      { title: 'Importar presentación', duration: '8 min' },
      { title: 'Exportar presentación', duration: '8 min' },
      { title: 'Guardar presentación', duration: '7 min' },
      { title: 'Administrar presentaciones', duration: '8 min' },
      { title: 'Eliminarlas', duration: '5 min' },
      { title: 'Copiarlas', duration: '5 min' },
      { title: 'Descargarlas', duration: '5 min' },
      { title: 'Iniciar', duration: '5 min' },
      { title: 'Iniciar sesiones', duration: '8 min' },
      { title: 'Seleccionar sesiones', duration: '5 min' },
      { title: 'Métodos de entrega', duration: '8 min' },
      { title: 'Ajustes de inicio de sesión', duration: '8 min' },
      { title: 'Carrera espacial', duration: '8 min' },
      { title: 'Elegir sesiones', duration: '5 min' },
      { title: 'Configurar equipos', duration: '8 min' },
      { title: 'Elegir ajustes', duration: '8 min' },
      { title: 'Pregunta final', duration: '5 min' },
      { title: 'Resultados', duration: '10 min' },
      { title: 'Compartir resultados', duration: '8 min' },
      { title: 'Exportar resultados', duration: '8 min' },
      { title: 'Informes', duration: '10 min' },
      { title: 'Buscar informes', duration: '8 min' },
      { title: 'Filtrar informes', duration: '8 min' },
      { title: 'Archivar informes', duration: '8 min' },
      { title: 'Eliminar informes', duration: '8 min' },
      { title: 'Configurar perfil', duration: '7 min' },
    ]
  },
  'trello': {
    title: 'Trello: Project Management',
    description: 'Learn how to use Trello for effective project management and team collaboration.',
    instructor: 'Laura Davis',
    instructorBio: 'Digital project manager with experience in agile methodologies.',
    instructorImage: 'https://randomuser.me/api/portraits/women/77.jpg',
    rating: 4.8,
    students: 140,
    duration: '2 hours',
    level: 'Intermediate',
    badge: '/assets/courses/badges/intermediate.png',
    lessons: [
      { title: '¿Qué es Trello?', duration: '5 min', completed: true },
      { title: 'Primeros pasos', duration: '8 min', completed: true },
      { title: 'Crear cuenta', duration: '7 min', completed: true },
      { title: 'Iniciar sesión', duration: '5 min' },
      { title: 'Conocer el menú', duration: '10 min' },
      { title: 'Clases', duration: '10 min' },
      { title: 'Cambiar nombre', duration: '5 min' },
      { title: 'Compartir clase', duration: '5 min' },
      { title: 'Inicio', duration: '5 min' },
      { title: 'Tableros', duration: '8 min' },
      { title: 'Crear tablero', duration: '10 min' },
      { title: 'Editar tablero', duration: '10 min' },
      { title: 'Configurar tablero', duration: '10 min' },
      { title: 'Compartir tablero', duration: '8 min' },
      { title: 'Importar tablero', duration: '8 min' },
      { title: 'Exportar tablero', duration: '8 min' },
      { title: 'Guardar tablero', duration: '7 min' },
      { title: 'Administrar tableros', duration: '8 min' },
      { title: 'Eliminarlas', duration: '5 min' },
      { title: 'Copiarlas', duration: '5 min' },
      { title: 'Descargarlas', duration: '5 min' },
      { title: 'Iniciar', duration: '5 min' },
      { title: 'Iniciar sesiones', duration: '8 min' },
      { title: 'Seleccionar sesiones', duration: '5 min' },
      { title: 'Métodos de entrega', duration: '8 min' },
      { title: 'Ajustes de inicio de sesión', duration: '8 min' },
      { title: 'Carrera espacial', duration: '8 min' },
      { title: 'Elegir sesiones', duration: '5 min' },
      { title: 'Configurar equipos', duration: '8 min' },
      { title: 'Elegir ajustes', duration: '8 min' },
      { title: 'Pregunta final', duration: '5 min' },
      { title: 'Resultados', duration: '10 min' },
      { title: 'Compartir resultados', duration: '8 min' },
      { title: 'Exportar resultados', duration: '8 min' },
      { title: 'Informes', duration: '10 min' },
      { title: 'Buscar informes', duration: '8 min' },
      { title: 'Filtrar informes', duration: '8 min' },
      { title: 'Archivar informes', duration: '8 min' },
      { title: 'Eliminar informes', duration: '8 min' },
      { title: 'Configurar perfil', duration: '7 min' },
    ]
  },
  'slack': {
    title: 'Slack: Team Communication',
    description: 'Learn how to use Slack for effective team communication and collaboration.',
    instructor: 'David Rodriguez',
    instructorBio: 'Digital communication specialist with experience in digital transformation.',
    instructorImage: 'https://randomuser.me/api/portraits/men/88.jpg',
    rating: 4.7,
    students: 160,
    duration: '2.5 hours',
    level: 'Intermediate',
    badge: '/assets/courses/badges/intermediate.png',
    lessons: [
      { title: '¿Qué es Slack?', duration: '5 min', completed: true },
      { title: 'Primeros pasos', duration: '8 min', completed: true },
      { title: 'Crear cuenta', duration: '7 min', completed: true },
      { title: 'Iniciar sesión', duration: '5 min' },
      { title: 'Conocer el menú', duration: '10 min' },
      { title: 'Clases', duration: '10 min' },
      { title: 'Cambiar nombre', duration: '5 min' },
      { title: 'Compartir clase', duration: '5 min' },
      { title: 'Inicio', duration: '5 min' },
      { title: 'Canales', duration: '8 min' },
      { title: 'Crear canal', duration: '10 min' },
      { title: 'Editar canal', duration: '10 min' },
      { title: 'Configurar canal', duration: '10 min' },
      { title: 'Compartir canal', duration: '8 min' },
      { title: 'Importar canal', duration: '8 min' },
      { title: 'Exportar canal', duration: '8 min' },
      { title: 'Guardar canal', duration: '7 min' },
      { title: 'Administrar canales', duration: '8 min' },
      { title: 'Eliminarlas', duration: '5 min' },
      { title: 'Copiarlas', duration: '5 min' },
      { title: 'Descargarlas', duration: '5 min' },
      { title: 'Iniciar', duration: '5 min' },
      { title: 'Iniciar sesiones', duration: '8 min' },
      { title: 'Seleccionar sesiones', duration: '5 min' },
      { title: 'Métodos de entrega', duration: '8 min' },
      { title: 'Ajustes de inicio de sesión', duration: '8 min' },
      { title: 'Carrera espacial', duration: '8 min' },
      { title: 'Elegir sesiones', duration: '5 min' },
      { title: 'Configurar equipos', duration: '8 min' },
      { title: 'Elegir ajustes', duration: '8 min' },
      { title: 'Pregunta final', duration: '5 min' },
      { title: 'Resultados', duration: '10 min' },
      { title: 'Compartir resultados', duration: '8 min' },
      { title: 'Exportar resultados', duration: '8 min' },
      { title: 'Informes', duration: '10 min' },
      { title: 'Buscar informes', duration: '8 min' },
      { title: 'Filtrar informes', duration: '8 min' },
      { title: 'Archivar informes', duration: '8 min' },
      { title: 'Eliminar informes', duration: '8 min' },
      { title: 'Configurar perfil', duration: '7 min' },
    ]
  },
  'zoom': {
    title: 'Zoom: Video Conferencing',
    description: 'Learn how to use Zoom for effective video conferencing and collaboration.',
    instructor: 'Sophia Martinez',
    instructorBio: 'Digital communication specialist with experience in digital transformation.',
    instructorImage: 'https://randomuser.me/api/portraits/women/99.jpg',
    rating: 4.8,
    students: 170,
    duration: '2.5 hours',
    level: 'Intermediate',
    badge: '/assets/courses/badges/intermediate.png',
    lessons: [
      { title: '¿Qué es Zoom?', duration: '5 min', completed: true },
      { title: 'Primeros pasos', duration: '8 min', completed: true },
      { title: 'Crear cuenta', duration: '7 min', completed: true },
      { title: 'Iniciar sesión', duration: '5 min' },
      { title: 'Conocer el menú', duration: '10 min' },
      { title: 'Clases', duration: '10 min' },
      { title: 'Cambiar nombre', duration: '5 min' },
      { title: 'Compartir clase', duration: '5 min' },
      { title: 'Inicio', duration: '5 min' },
      { title: 'Reuniones', duration: '8 min' },
      { title: 'Crear reunión', duration: '10 min' },
      { title: 'Editar reunión', duration: '10 min' },
      { title: 'Configurar reunión', duration: '10 min' },
      { title: 'Compartir reunión', duration: '8 min' },
      { title: 'Importar reunión', duration: '8 min' },
      { title: 'Exportar reunión', duration: '8 min' },
      { title: 'Guardar reunión', duration: '7 min' },
      { title: 'Administrar reuniones', duration: '8 min' },
      { title: 'Eliminarlas', duration: '5 min' },
      { title: 'Copiarlas', duration: '5 min' },
      { title: 'Descargarlas', duration: '5 min' },
      { title: 'Iniciar', duration: '5 min' },
      { title: 'Iniciar sesiones', duration: '8 min' },
      { title: 'Seleccionar sesiones', duration: '5 min' },
      { title: 'Métodos de entrega', duration: '8 min' },
      { title: 'Ajustes de inicio de sesión', duration: '8 min' },
      { title: 'Carrera espacial', duration: '8 min' },
      { title: 'Elegir sesiones', duration: '5 min' },
      { title: 'Configurar equipos', duration: '8 min' },
      { title: 'Elegir ajustes', duration: '8 min' },
      { title: 'Pregunta final', duration: '5 min' },
      { title: 'Resultados', duration: '10 min' },
      { title: 'Compartir resultados', duration: '8 min' },
      { title: 'Exportar resultados', duration: '8 min' },
      { title: 'Informes', duration: '10 min' },
      { title: 'Buscar informes', duration: '8 min' },
      { title: 'Filtrar informes', duration: '8 min' },
      { title: 'Archivar informes', duration: '8 min' },
      { title: 'Eliminar informes', duration: '8 min' },
      { title: 'Configurar perfil', duration: '7 min' },
    ]
  },
  'notion': {
    title: 'Notion: Project Management',
    description: 'Learn how to use Notion for effective project management and team collaboration.',
    instructor: 'James Wilson',
    instructorBio: 'Digital project manager with experience in agile methodologies.',
    instructorImage: 'https://randomuser.me/api/portraits/men/11.jpg',
    rating: 4.8,
    students: 180,
    duration: '2.5 hours',
    level: 'Intermediate',
    badge: '/assets/courses/badges/intermediate.png',
    lessons: [
      { title: '¿Qué es Notion?', duration: '5 min', completed: true },
      { title: 'Primeros pasos', duration: '8 min', completed: true },
      { title: 'Crear cuenta', duration: '7 min', completed: true },
      { title: 'Iniciar sesión', duration: '5 min' },
      { title: 'Conocer el menú', duration: '10 min' },
      { title: 'Clases', duration: '10 min' },
      { title: 'Cambiar nombre', duration: '5 min' },
      { title: 'Compartir clase', duration: '5 min' },
      { title: 'Inicio', duration: '5 min' },
      { title: 'Tableros', duration: '8 min' },
      { title: 'Crear tablero', duration: '10 min' },
      { title: 'Editar tablero', duration: '10 min' },
      { title: 'Configurar tablero', duration: '10 min' },
      { title: 'Compartir tablero', duration: '8 min' },
      { title: 'Importar tablero', duration: '8 min' },
      { title: 'Exportar tablero', duration: '8 min' },
      { title: 'Guardar tablero', duration: '7 min' },
      { title: 'Administrar tableros', duration: '8 min' },
      { title: 'Eliminarlas', duration: '5 min' },
      { title: 'Copiarlas', duration: '5 min' },
      { title: 'Descargarlas', duration: '5 min' },
      { title: 'Iniciar', duration: '5 min' },
      { title: 'Iniciar sesiones', duration: '8 min' },
      { title: 'Seleccionar sesiones', duration: '5 min' },
      { title: 'Métodos de entrega', duration: '8 min' },
      { title: 'Ajustes de inicio de sesión', duration: '8 min' },
      { title: 'Carrera espacial', duration: '8 min' },
      { title: 'Elegir sesiones', duration: '5 min' },
      { title: 'Configurar equipos', duration: '8 min' },
      { title: 'Elegir ajustes', duration: '8 min' },
      { title: 'Pregunta final', duration: '5 min' },
      { title: 'Resultados', duration: '10 min' },
      { title: 'Compartir resultados', duration: '8 min' },
      { title: 'Exportar resultados', duration: '8 min' },
      { title: 'Informes', duration: '10 min' },
      { title: 'Buscar informes', duration: '8 min' },
      { title: 'Filtrar informes', duration: '8 min' },
      { title: 'Archivar informes', duration: '8 min' },
      { title: 'Eliminar informes', duration: '8 min' },
      { title: 'Configurar perfil', duration: '7 min' },
    ]
  },
  'fiverr': {
    title: 'Fiverr: Freelancing Platform',
    description: 'Learn how to use Fiverr for finding freelance work and managing your portfolio.',
    instructor: 'Emma Thompson',
    instructorBio: 'Digital freelancer with experience in digital marketing and web development.',
    instructorImage: 'https://randomuser.me/api/portraits/women/22.jpg',
    rating: 4.7,
    students: 190,
    duration: '2.5 hours',
    level: 'Intermediate',
    badge: '/assets/courses/badges/intermediate.png',
    lessons: [
      { title: '¿Qué es Fiverr?', duration: '5 min', completed: true },
      { title: 'Primeros pasos', duration: '8 min', completed: true },
      { title: 'Crear cuenta', duration: '7 min', completed: true },
      { title: 'Iniciar sesión', duration: '5 min' },
      { title: 'Conocer el menú', duration: '10 min' },
      { title: 'Clases', duration: '10 min' },
      { title: 'Cambiar nombre', duration: '5 min' },
      { title: 'Compartir clase', duration: '5 min' },
      { title: 'Inicio', duration: '5 min' },
      { title: 'Gig', duration: '8 min' },
      { title: 'Crear gig', duration: '10 min' },
      { title: 'Editar gig', duration: '10 min' },
      { title: 'Configurar gig', duration: '10 min' },
      { title: 'Compartir gig', duration: '8 min' },
      { title: 'Importar gig', duration: '8 min' },
      { title: 'Exportar gig', duration: '8 min' },
      { title: 'Guardar gig', duration: '7 min' },
      { title: 'Administrar gigs', duration: '8 min' },
      { title: 'Eliminarlas', duration: '5 min' },
      { title: 'Copiarlas', duration: '5 min' },
      { title: 'Descargarlas', duration: '5 min' },
      { title: 'Iniciar', duration: '5 min' },
      { title: 'Iniciar sesiones', duration: '8 min' },
      { title: 'Seleccionar sesiones', duration: '5 min' },
      { title: 'Métodos de entrega', duration: '8 min' },
      { title: 'Ajustes de inicio de sesión', duration: '8 min' },
      { title: 'Carrera espacial', duration: '8 min' },
      { title: 'Elegir sesiones', duration: '5 min' },
      { title: 'Configurar equipos', duration: '8 min' },
      { title: 'Elegir ajustes', duration: '8 min' },
      { title: 'Pregunta final', duration: '5 min' },
      { title: 'Resultados', duration: '10 min' },
      { title: 'Compartir resultados', duration: '8 min' },
      { title: 'Exportar resultados', duration: '8 min' },
      { title: 'Informes', duration: '10 min' },
      { title: 'Buscar informes', duration: '8 min' },
      { title: 'Filtrar informes', duration: '8 min' },
      { title: 'Archivar informes', duration: '8 min' },
      { title: 'Eliminar informes', duration: '8 min' },
      { title: 'Configurar perfil', duration: '7 min' },
    ]
  },
  'upwork': {
    title: 'Upwork: Freelancing Platform',
    description: 'Learn how to use Upwork for finding freelance work and managing your portfolio.',
    instructor: 'David Rodriguez',
    instructorBio: 'Digital communication specialist with experience in digital transformation.',
    instructorImage: 'https://randomuser.me/api/portraits/men/88.jpg',
    rating: 4.7,
    students: 160,
    duration: '2.5 hours',
    level: 'Intermediate',
    badge: '/assets/courses/badges/intermediate.png',
    lessons: [
      { title: '¿Qué es Upwork?', duration: '5 min', completed: true },
      { title: 'Primeros pasos', duration: '8 min', completed: true },
      { title: 'Crear cuenta', duration: '7 min', completed: true },
      { title: 'Iniciar sesión', duration: '5 min' },
      { title: 'Conocer el menú', duration: '10 min' },
      { title: 'Clases', duration: '10 min' },
      { title: 'Cambiar nombre', duration: '5 min' },
      { title: 'Compartir clase', duration: '5 min' },
      { title: 'Inicio', duration: '5 min' },
      { title: 'Gig', duration: '8 min' },
      { title: 'Crear gig', duration: '10 min' },
      { title: 'Editar gig', duration: '10 min' },
      { title: 'Configurar gig', duration: '10 min' },
      { title: 'Compartir gig', duration: '8 min' },
      { title: 'Importar gig', duration: '8 min' },
      { title: 'Exportar gig', duration: '8 min' },
      { title: 'Guardar gig', duration: '7 min' },
      { title: 'Administrar gigs', duration: '8 min' },
      { title: 'Eliminarlas', duration: '5 min' },
      { title: 'Copiarlas', duration: '5 min' },
      { title: 'Descargarlas', duration: '5 min' },
      { title: 'Iniciar', duration: '5 min' },
      { title: 'Iniciar sesiones', duration: '8 min' },
      { title: 'Seleccionar sesiones', duration: '5 min' },
      { title: 'Métodos de entrega', duration: '8 min' },
      { title: 'Ajustes de inicio de sesión', duration: '8 min' },
      { title: 'Carrera espacial', duration: '8 min' },
      { title: 'Elegir sesiones', duration: '5 min' },
      { title: 'Configurar equipos', duration: '8 min' },
      { title: 'Elegir ajustes', duration: '8 min' },
      { title: 'Pregunta final', duration: '5 min' },
      { title: 'Resultados', duration: '10 min' },
      { title: 'Compartir resultados', duration: '8 min' },
      { title: 'Exportar resultados', duration: '8 min' },
      { title: 'Informes', duration: '10 min' },
      { title: 'Buscar informes', duration: '8 min' },
      { title: 'Filtrar informes', duration: '8 min' },
      { title: 'Archivar informes', duration: '8 min' },
      { title: 'Eliminar informes', duration: '8 min' },
      { title: 'Configurar perfil', duration: '7 min' },
    ]
  },
  'wayground': {
    title: 'Wayground: Digital Marketing',
    description: 'Learn how to use Wayground for effective digital marketing strategies and content creation.',
    instructor: 'Alex Thompson',
    instructorBio: 'Digital marketing expert with 10+ years experience in SEO, content marketing, and social media.',
    instructorImage: 'https://randomuser.me/api/portraits/men/12.jpg',
    rating: 4.7,
    students: 200,
    duration: '2.5 hours',
    level: 'Intermediate',
    badge: '/assets/courses/badges/intermediate.png',
    lessons: [
      { title: '¿Qué es Wayground?', duration: '5 min', completed: true },
      { title: 'Primeros pasos', duration: '8 min', completed: true },
      { title: 'Crear cuenta', duration: '7 min', completed: true },
      { title: 'Iniciar sesión', duration: '5 min' },
      { title: 'Conocer el menú', duration: '10 min' },
      { title: 'Clases', duration: '10 min' },
      { title: 'Cambiar nombre', duration: '5 min' },
      { title: 'Compartir clase', duration: '5 min' },
      { title: 'Inicio', duration: '5 min' },
      { title: 'Marketing', duration: '8 min' },
      { title: 'Crear contenido', duration: '10 min' },
      { title: 'Editar contenido', duration: '10 min' },
      { title: 'Configurar contenido', duration: '10 min' },
      { title: 'Compartir contenido', duration: '8 min' },
      { title: 'Importar contenido', duration: '8 min' },
      { title: 'Exportar contenido', duration: '8 min' },
      { title: 'Guardar contenido', duration: '7 min' },
      { title: 'Administrar contenido', duration: '8 min' },
      { title: 'Eliminarlas', duration: '5 min' },
      { title: 'Copiarlas', duration: '5 min' },
      { title: 'Descargarlas', duration: '5 min' },
      { title: 'Iniciar', duration: '5 min' },
      { title: 'Iniciar sesiones', duration: '8 min' },
      { title: 'Seleccionar sesiones', duration: '5 min' },
      { title: 'Métodos de entrega', duration: '8 min' },
      { title: 'Ajustes de inicio de sesión', duration: '8 min' },
      { title: 'Carrera espacial', duration: '8 min' },
      { title: 'Elegir sesiones', duration: '5 min' },
      { title: 'Configurar equipos', duration: '8 min' },
      { title: 'Elegir ajustes', duration: '8 min' },
      { title: 'Pregunta final', duration: '5 min' },
      { title: 'Resultados', duration: '10 min' },
      { title: 'Compartir resultados', duration: '8 min' },
      { title: 'Exportar resultados', duration: '8 min' },
      { title: 'Informes', duration: '10 min' },
      { title: 'Buscar informes', duration: '8 min' },
      { title: 'Filtrar informes', duration: '8 min' },
      { title: 'Archivar informes', duration: '8 min' },
      { title: 'Eliminar informes', duration: '8 min' },
      { title: 'Configurar perfil', duration: '7 min' },
    ]
  },
  'visme': {
    title: 'Visme: Presentation Design',
    description: 'Learn how to create stunning presentations using Visme.',
    instructor: 'Lisa Chen',
    instructorBio: 'Digital design specialist with experience in presentation design and animation.',
    instructorImage: 'https://randomuser.me/api/portraits/women/78.jpg',
    rating: 4.7,
    students: 140,
    duration: '2 hours',
    level: 'Intermediate',
    badge: '/assets/courses/badges/intermediate.png',
    lessons: [
      { title: '¿Qué es Visme?', duration: '5 min', completed: true },
      { title: 'Primeros pasos', duration: '8 min', completed: true },
      { title: 'Crear cuenta', duration: '7 min', completed: true },
      { title: 'Iniciar sesión', duration: '5 min' },
      { title: 'Conocer el menú', duration: '10 min' },
      { title: 'Clases', duration: '10 min' },
      { title: 'Cambiar nombre', duration: '5 min' },
      { title: 'Compartir clase', duration: '5 min' },
      { title: 'Inicio', duration: '5 min' },
      { title: 'Presentaciones', duration: '8 min' },
      { title: 'Crear presentación', duration: '10 min' },
      { title: 'Editar presentación', duration: '10 min' },
      { title: 'Configurar presentación', duration: '10 min' },
      { title: 'Compartir presentación', duration: '8 min' },
      { title: 'Importar presentación', duration: '8 min' },
      { title: 'Exportar presentación', duration: '8 min' },
      { title: 'Guardar presentación', duration: '7 min' },
      { title: 'Administrar presentaciones', duration: '8 min' },
      { title: 'Eliminarlas', duration: '5 min' },
      { title: 'Copiarlas', duration: '5 min' },
      { title: 'Descargarlas', duration: '5 min' },
      { title: 'Iniciar', duration: '5 min' },
      { title: 'Iniciar sesiones', duration: '8 min' },
      { title: 'Seleccionar sesiones', duration: '5 min' },
      { title: 'Métodos de entrega', duration: '8 min' },
      { title: 'Ajustes de inicio de sesión', duration: '8 min' },
      { title: 'Carrera espacial', duration: '8 min' },
      { title: 'Elegir sesiones', duration: '5 min' },
      { title: 'Configurar equipos', duration: '8 min' },
      { title: 'Elegir ajustes', duration: '8 min' },
      { title: 'Pregunta final', duration: '5 min' },
      { title: 'Resultados', duration: '10 min' },
      { title: 'Compartir resultados', duration: '8 min' },
      { title: 'Exportar resultados', duration: '8 min' },
      { title: 'Informes', duration: '10 min' },
      { title: 'Buscar informes', duration: '8 min' },
      { title: 'Filtrar informes', duration: '8 min' },
      { title: 'Archivar informes', duration: '8 min' },
      { title: 'Eliminar informes', duration: '8 min' },
      { title: 'Configurar perfil', duration: '7 min' },
    ]
  },
  'adobe-express': {
    title: 'Adobe Express: Design Made Easy',
    description: 'Learn how to use Adobe Express for creating stunning designs with ease.',
    instructor: 'Peter Jones',
    instructorBio: 'Digital design specialist with experience in Adobe Creative Suite.',
    instructorImage: 'https://randomuser.me/api/portraits/men/90.jpg',
    rating: 4.8,
    students: 150,
    duration: '2 hours',
    level: 'Beginner',
    badge: '/assets/courses/badges/beginner.png',
    lessons: [
      { title: '¿Qué es Adobe Express?', duration: '5 min', completed: true },
      { title: 'Primeros pasos', duration: '8 min', completed: true },
      { title: 'Crear cuenta', duration: '7 min', completed: true },
      { title: 'Iniciar sesión', duration: '5 min' },
      { title: 'Conocer el menú', duration: '10 min' },
      { title: 'Clases', duration: '10 min' },
      { title: 'Cambiar nombre', duration: '5 min' },
      { title: 'Compartir clase', duration: '5 min' },
      { title: 'Inicio', duration: '5 min' },
      { title: 'Diseño', duration: '8 min' },
      { title: 'Crear diseño', duration: '10 min' },
      { title: 'Editar diseño', duration: '10 min' },
      { title: 'Configurar diseño', duration: '10 min' },
      { title: 'Compartir diseño', duration: '8 min' },
      { title: 'Importar diseño', duration: '8 min' },
      { title: 'Exportar diseño', duration: '8 min' },
      { title: 'Guardar diseño', duration: '7 min' },
      { title: 'Administrar diseños', duration: '8 min' },
      { title: 'Eliminarlas', duration: '5 min' },
      { title: 'Copiarlas', duration: '5 min' },
      { title: 'Descargarlas', duration: '5 min' },
      { title: 'Iniciar', duration: '5 min' },
      { title: 'Iniciar sesiones', duration: '8 min' },
      { title: 'Seleccionar sesiones', duration: '5 min' },
      { title: 'Métodos de entrega', duration: '8 min' },
      { title: 'Ajustes de inicio de sesión', duration: '8 min' },
      { title: 'Carrera espacial', duration: '8 min' },
      { title: 'Elegir sesiones', duration: '5 min' },
      { title: 'Configurar equipos', duration: '8 min' },
      { title: 'Elegir ajustes', duration: '8 min' },
      { title: 'Pregunta final', duration: '5 min' },
      { title: 'Resultados', duration: '10 min' },
      { title: 'Compartir resultados', duration: '8 min' },
      { title: 'Exportar resultados', duration: '8 min' },
      { title: 'Informes', duration: '10 min' },
      { title: 'Buscar informes', duration: '8 min' },
      { title: 'Filtrar informes', duration: '8 min' },
      { title: 'Archivar informes', duration: '8 min' },
      { title: 'Eliminar informes', duration: '8 min' },
      { title: 'Configurar perfil', duration: '7 min' },
    ]
  },
  'google-classroom': {
    title: 'Google Classroom: Digital Learning',
    description: 'Learn how to use Google Classroom for effective digital learning and classroom management.',
    instructor: 'Sarah Johnson',
    instructorBio: 'Digital education specialist with experience in Google Workspace and digital learning tools.',
    instructorImage: 'https://randomuser.me/api/portraits/women/44.jpg',
    rating: 4.9,
    students: 2100,
    duration: '2 hours',
    level: 'Beginner',
    badge: '/assets/courses/badges/beginner.png',
    lessons: [
      { title: '¿Qué es Google Classroom?', duration: '5 min', completed: true },
      { title: 'Primeros pasos', duration: '8 min', completed: true },
      { title: 'Crear cuenta', duration: '7 min', completed: true },
      { title: 'Iniciar sesión', duration: '5 min' },
      { title: 'Conocer el menú', duration: '10 min' },
      { title: 'Clases', duration: '10 min' },
      { title: 'Cambiar nombre', duration: '5 min' },
      { title: 'Compartir clase', duration: '5 min' },
      { title: 'Inicio', duration: '5 min' },
      { title: 'Clases', duration: '8 min' },
      { title: 'Crear clase', duration: '10 min' },
      { title: 'Editar clase', duration: '10 min' },
      { title: 'Configurar clase', duration: '10 min' },
      { title: 'Compartir clase', duration: '8 min' },
      { title: 'Importar clase', duration: '8 min' },
      { title: 'Exportar clase', duration: '8 min' },
      { title: 'Guardar clase', duration: '7 min' },
      { title: 'Administrar clases', duration: '8 min' },
      { title: 'Eliminarlas', duration: '5 min' },
      { title: 'Copiarlas', duration: '5 min' },
      { title: 'Descargarlas', duration: '5 min' },
      { title: 'Iniciar', duration: '5 min' },
      { title: 'Iniciar sesiones', duration: '8 min' },
      { title: 'Seleccionar sesiones', duration: '5 min' },
      { title: 'Métodos de entrega', duration: '8 min' },
      { title: 'Ajustes de inicio de sesión', duration: '8 min' },
      { title: 'Carrera espacial', duration: '8 min' },
      { title: 'Elegir sesiones', duration: '5 min' },
      { title: 'Configurar equipos', duration: '8 min' },
      { title: 'Elegir ajustes', duration: '8 min' },
      { title: 'Pregunta final', duration: '5 min' },
      { title: 'Resultados', duration: '10 min' },
      { title: 'Compartir resultados', duration: '8 min' },
      { title: 'Exportar resultados', duration: '8 min' },
      { title: 'Informes', duration: '10 min' },
      { title: 'Buscar informes', duration: '8 min' },
      { title: 'Filtrar informes', duration: '8 min' },
      { title: 'Archivar informes', duration: '8 min' },
      { title: 'Eliminar informes', duration: '8 min' },
      { title: 'Configurar perfil', duration: '7 min' },
    ]
  },
  'google-suite': {
    title: 'Google Suite: Productivity Tools',
    description: 'Learn how to use Google Suite for effective productivity and collaboration.',
    instructor: 'Mike Chen',
    instructorBio: 'Google Workspace certified trainer helping teams work smarter. Mike has trained thousands of users in productivity tools.',
    instructorImage: 'https://randomuser.me/api/portraits/men/13.jpg',
    rating: 4.9,
    students: 2500,
    duration: '2.5 hours',
    level: 'Beginner',
    badge: '/assets/courses/badges/beginner.png',
    lessons: [
      { title: '¿Qué es Google Suite?', duration: '5 min', completed: true },
      { title: 'Primeros pasos', duration: '8 min', completed: true },
      { title: 'Crear cuenta', duration: '7 min', completed: true },
      { title: 'Iniciar sesión', duration: '5 min' },
      { title: 'Conocer el menú', duration: '10 min' },
      { title: 'Clases', duration: '10 min' },
      { title: 'Cambiar nombre', duration: '5 min' },
      { title: 'Compartir clase', duration: '5 min' },
      { title: 'Inicio', duration: '5 min' },
      { title: 'Suite', duration: '8 min' },
      { title: 'Gmail', duration: '10 min' },
      { title: 'Docs', duration: '10 min' },
      { title: 'Sheets', duration: '10 min' },
      { title: 'Drive', duration: '10 min' },
      { title: 'Calendar', duration: '10 min' },
      { title: 'Meet', duration: '10 min' },
      { title: 'Forms', duration: '10 min' },
      { title: 'Jamboard', duration: '10 min' },
      { title: 'Configurar cuenta', duration: '10 min' },
      { title: 'Compartir cuenta', duration: '8 min' },
      { title: 'Importar cuenta', duration: '8 min' },
      { title: 'Exportar cuenta', duration: '8 min' },
      { title: 'Guardar cuenta', duration: '7 min' },
      { title: 'Administrar cuenta', duration: '8 min' },
      { title: 'Eliminarlas', duration: '5 min' },
      { title: 'Copiarlas', duration: '5 min' },
      { title: 'Descargarlas', duration: '5 min' },
      { title: 'Iniciar', duration: '5 min' },
      { title: 'Iniciar sesiones', duration: '8 min' },
      { title: 'Seleccionar sesiones', duration: '5 min' },
      { title: 'Métodos de entrega', duration: '8 min' },
      { title: 'Ajustes de inicio de sesión', duration: '8 min' },
      { title: 'Carrera espacial', duration: '8 min' },
      { title: 'Elegir sesiones', duration: '5 min' },
      { title: 'Configurar equipos', duration: '8 min' },
      { title: 'Elegir ajustes', duration: '8 min' },
      { title: 'Pregunta final', duration: '5 min' },
      { title: 'Resultados', duration: '10 min' },
      { title: 'Compartir resultados', duration: '8 min' },
      { title: 'Exportar resultados', duration: '8 min' },
      { title: 'Informes', duration: '10 min' },
      { title: 'Buscar informes', duration: '8 min' },
      { title: 'Filtrar informes', duration: '8 min' },
      { title: 'Archivar informes', duration: '8 min' },
      { title: 'Eliminar informes', duration: '8 min' },
      { title: 'Configurar perfil', duration: '7 min' },
    ]
  },
  'powtoon': {
    title: 'Powtoon: Video Animation',
    description: 'Learn how to create engaging animated videos using Powtoon.',
    instructor: 'Ana Torres',
    instructorBio: 'Digital design specialist with experience in presentation design and animation.',
    instructorImage: 'https://randomuser.me/api/portraits/women/44.jpg',
    rating: 4.7,
    students: 160,
    duration: '2 hours',
    level: 'Intermediate',
    badge: '/assets/courses/badges/intermediate.png',
    lessons: [
      { title: '¿Qué es Powtoon?', duration: '5 min', completed: true },
      { title: 'Primeros pasos', duration: '8 min', completed: true },
      { title: 'Crear cuenta', duration: '7 min', completed: true },
      { title: 'Iniciar sesión', duration: '5 min' },
      { title: 'Conocer el menú', duration: '10 min' },
      { title: 'Clases', duration: '10 min' },
      { title: 'Cambiar nombre', duration: '5 min' },
      { title: 'Compartir clase', duration: '5 min' },
      { title: 'Inicio', duration: '5 min' },
      { title: 'Animaciones', duration: '8 min' },
      { title: 'Crear animación', duration: '10 min' },
      { title: 'Editar animación', duration: '10 min' },
      { title: 'Configurar animación', duration: '10 min' },
      { title: 'Compartir animación', duration: '8 min' },
      { title: 'Importar animación', duration: '8 min' },
      { title: 'Exportar animación', duration: '8 min' },
      { title: 'Guardar animación', duration: '7 min' },
      { title: 'Administrar animaciones', duration: '8 min' },
      { title: 'Eliminarlas', duration: '5 min' },
      { title: 'Copiarlas', duration: '5 min' },
      { title: 'Descargarlas', duration: '5 min' },
      { title: 'Iniciar', duration: '5 min' },
      { title: 'Iniciar sesiones', duration: '8 min' },
      { title: 'Seleccionar sesiones', duration: '5 min' },
      { title: 'Métodos de entrega', duration: '8 min' },
      { title: 'Ajustes de inicio de sesión', duration: '8 min' },
      { title: 'Carrera espacial', duration: '8 min' },
      { title: 'Elegir sesiones', duration: '5 min' },
      { title: 'Configurar equipos', duration: '8 min' },
      { title: 'Elegir ajustes', duration: '8 min' },
      { title: 'Pregunta final', duration: '5 min' },
      { title: 'Resultados', duration: '10 min' },
      { title: 'Compartir resultados', duration: '8 min' },
      { title: 'Exportar resultados', duration: '8 min' },
      { title: 'Informes', duration: '10 min' },
      { title: 'Buscar informes', duration: '8 min' },
      { title: 'Filtrar informes', duration: '8 min' },
      { title: 'Archivar informes', duration: '8 min' },
      { title: 'Eliminar informes', duration: '8 min' },
      { title: 'Configurar perfil', duration: '7 min' },
    ]
  },
  'moovly': {
    title: 'Moovly: Video Creation',
    description: 'Learn how to create professional videos using Moovly.',
    instructor: 'David Rodriguez',
    instructorBio: 'Digital communication specialist with experience in digital transformation.',
    instructorImage: 'https://randomuser.me/api/portraits/men/88.jpg',
    rating: 4.7,
    students: 170,
    duration: '2.5 hours',
    level: 'Intermediate',
    badge: '/assets/courses/badges/intermediate.png',
    lessons: [
      { title: '¿Qué es Moovly?', duration: '5 min', completed: true },
      { title: 'Primeros pasos', duration: '8 min', completed: true },
      { title: 'Crear cuenta', duration: '7 min', completed: true },
      { title: 'Iniciar sesión', duration: '5 min' },
      { title: 'Conocer el menú', duration: '10 min' },
      { title: 'Clases', duration: '10 min' },
      { title: 'Cambiar nombre', duration: '5 min' },
      { title: 'Compartir clase', duration: '5 min' },
      { title: 'Inicio', duration: '5 min' },
      { title: 'Videos', duration: '8 min' },
      { title: 'Crear video', duration: '10 min' },
      { title: 'Editar video', duration: '10 min' },
      { title: 'Configurar video', duration: '10 min' },
      { title: 'Compartir video', duration: '8 min' },
      { title: 'Importar video', duration: '8 min' },
      { title: 'Exportar video', duration: '8 min' },
      { title: 'Guardar video', duration: '7 min' },
      { title: 'Administrar videos', duration: '8 min' },
      { title: 'Eliminarlas', duration: '5 min' },
      { title: 'Copiarlas', duration: '5 min' },
      { title: 'Descargarlas', duration: '5 min' },
      { title: 'Iniciar', duration: '5 min' },
      { title: 'Iniciar sesiones', duration: '8 min' },
      { title: 'Seleccionar sesiones', duration: '5 min' },
      { title: 'Métodos de entrega', duration: '8 min' },
      { title: 'Ajustes de inicio de sesión', duration: '8 min' },
      { title: 'Carrera espacial', duration: '8 min' },
      { title: 'Elegir sesiones', duration: '5 min' },
      { title: 'Configurar equipos', duration: '8 min' },
      { title: 'Elegir ajustes', duration: '8 min' },
      { title: 'Pregunta final', duration: '5 min' },
      { title: 'Resultados', duration: '10 min' },
      { title: 'Compartir resultados', duration: '8 min' },
      { title: 'Exportar resultados', duration: '8 min' },
      { title: 'Informes', duration: '10 min' },
      { title: 'Buscar informes', duration: '8 min' },
      { title: 'Filtrar informes', duration: '8 min' },
      { title: 'Archivar informes', duration: '8 min' },
      { title: 'Eliminar informes', duration: '8 min' },
      { title: 'Configurar perfil', duration: '7 min' },
    ]
  },
  'duolingo': {
    title: 'Duolingo: Language Learning',
    description: 'Learn how to use Duolingo for effective language learning and vocabulary building.',
    instructor: 'Emma Thompson',
    instructorBio: 'Digital freelancer with experience in digital marketing and web development.',
    instructorImage: 'https://randomuser.me/api/portraits/women/22.jpg',
    rating: 4.7,
    students: 190,
    duration: '2.5 hours',
    level: 'Beginner',
    badge: '/assets/courses/badges/beginner.png',
    lessons: [
      { title: '¿Qué es Duolingo?', duration: '5 min', completed: true },
      { title: 'Primeros pasos', duration: '8 min', completed: true },
      { title: 'Crear cuenta', duration: '7 min', completed: true },
      { title: 'Iniciar sesión', duration: '5 min' },
      { title: 'Conocer el menú', duration: '10 min' },
      { title: 'Clases', duration: '10 min' },
      { title: 'Cambiar nombre', duration: '5 min' },
      { title: 'Compartir clase', duration: '5 min' },
      { title: 'Inicio', duration: '5 min' },
      { title: 'Lecciones', duration: '8 min' },
      { title: 'Aprender palabras', duration: '10 min' },
      { title: 'Practica con ejercicios', duration: '10 min' },
      { title: 'Repite lecciones', duration: '10 min' },
      { title: 'Jugar juegos', duration: '10 min' },
      { title: 'Configurar preferencias', duration: '10 min' },
      { title: 'Compartir cuenta', duration: '8 min' },
      { title: 'Importar cuenta', duration: '8 min' },
      { title: 'Exportar cuenta', duration: '8 min' },
      { title: 'Guardar cuenta', duration: '7 min' },
      { title: 'Administrar cuenta', duration: '8 min' },
      { title: 'Eliminarlas', duration: '5 min' },
      { title: 'Copiarlas', duration: '5 min' },
      { title: 'Descargarlas', duration: '5 min' },
      { title: 'Iniciar', duration: '5 min' },
      { title: 'Iniciar sesiones', duration: '8 min' },
      { title: 'Seleccionar sesiones', duration: '5 min' },
      { title: 'Métodos de entrega', duration: '8 min' },
      { title: 'Ajustes de inicio de sesión', duration: '8 min' },
      { title: 'Carrera espacial', duration: '8 min' },
      { title: 'Elegir sesiones', duration: '5 min' },
      { title: 'Configurar equipos', duration: '8 min' },
      { title: 'Elegir ajustes', duration: '8 min' },
      { title: 'Pregunta final', duration: '5 min' },
      { title: 'Resultados', duration: '10 min' },
      { title: 'Compartir resultados', duration: '8 min' },
      { title: 'Exportar resultados', duration: '8 min' },
      { title: 'Informes', duration: '10 min' },
      { title: 'Buscar informes', duration: '8 min' },
      { title: 'Filtrar informes', duration: '8 min' },
      { title: 'Archivar informes', duration: '8 min' },
      { title: 'Eliminar informes', duration: '8 min' },
      { title: 'Configurar perfil', duration: '7 min' },
    ]
  },
  'google-scholar': {
    title: 'Google Scholar: Research',
    description: 'Learn how to use Google Scholar for effective academic research and citation management.',
    instructor: 'Dr. Emily Rodriguez',
    instructorBio: 'PhD in Computer Science with focus on digital safety education. Emily is passionate about making cybersecurity accessible to everyone.',
    instructorImage: 'https://randomuser.me/api/portraits/women/44.jpg',
    rating: 4.7,
    students: 180,
    duration: '2.5 hours',
    level: 'Intermediate',
    badge: '/assets/courses/badges/intermediate.png',
    lessons: [
      { title: '¿Qué es Google Scholar?', duration: '5 min', completed: true },
      { title: 'Primeros pasos', duration: '8 min', completed: true },
      { title: 'Crear cuenta', duration: '7 min', completed: true },
      { title: 'Iniciar sesión', duration: '5 min' },
      { title: 'Conocer el menú', duration: '10 min' },
      { title: 'Clases', duration: '10 min' },
      { title: 'Cambiar nombre', duration: '5 min' },
      { title: 'Compartir clase', duration: '5 min' },
      { title: 'Inicio', duration: '5 min' },
      { title: 'Búsqueda', duration: '8 min' },
      { title: 'Filtros', duration: '10 min' },
      { title: 'Citas', duration: '10 min' },
      { title: 'Bibliografía', duration: '10 min' },
      { title: 'Configurar cuenta', duration: '10 min' },
      { title: 'Compartir cuenta', duration: '8 min' },
      { title: 'Importar cuenta', duration: '8 min' },
      { title: 'Exportar cuenta', duration: '8 min' },
      { title: 'Guardar cuenta', duration: '7 min' },
      { title: 'Administrar cuenta', duration: '8 min' },
      { title: 'Eliminarlas', duration: '5 min' },
      { title: 'Copiarlas', duration: '5 min' },
      { title: 'Descargarlas', duration: '5 min' },
      { title: 'Iniciar', duration: '5 min' },
      { title: 'Iniciar sesiones', duration: '8 min' },
      { title: 'Seleccionar sesiones', duration: '5 min' },
      { title: 'Métodos de entrega', duration: '8 min' },
      { title: 'Ajustes de inicio de sesión', duration: '8 min' },
      { title: 'Carrera espacial', duration: '8 min' },
      { title: 'Elegir sesiones', duration: '5 min' },
      { title: 'Configurar equipos', duration: '8 min' },
      { title: 'Elegir ajustes', duration: '8 min' },
      { title: 'Pregunta final', duration: '5 min' },
      { title: 'Resultados', duration: '10 min' },
      { title: 'Compartir resultados', duration: '8 min' },
      { title: 'Exportar resultados', duration: '8 min' },
      { title: 'Informes', duration: '10 min' },
      { title: 'Buscar informes', duration: '8 min' },
      { title: 'Filtrar informes', duration: '8 min' },
      { title: 'Archivar informes', duration: '8 min' },
      { title: 'Eliminar informes', duration: '8 min' },
      { title: 'Configurar perfil', duration: '7 min' },
    ]
  },
  'khan-academy': {
    title: 'Khan Academy: Math and Science',
    description: 'Learn how to use Khan Academy for effective math and science education.',
    instructor: 'Peter Jones',
    instructorBio: 'Digital design specialist with experience in Adobe Creative Suite.',
    instructorImage: 'https://randomuser.me/api/portraits/men/90.jpg',
    rating: 4.8,
    students: 200,
    duration: '2.5 hours',
    level: 'Beginner',
    badge: '/assets/courses/badges/beginner.png',
    lessons: [
      { title: '¿Qué es Khan Academy?', duration: '5 min', completed: true },
      { title: 'Primeros pasos', duration: '8 min', completed: true },
      { title: 'Crear cuenta', duration: '7 min', completed: true },
      { title: 'Iniciar sesión', duration: '5 min' },
      { title: 'Conocer el menú', duration: '10 min' },
      { title: 'Clases', duration: '10 min' },
      { title: 'Cambiar nombre', duration: '5 min' },
      { title: 'Compartir clase', duration: '5 min' },
      { title: 'Inicio', duration: '5 min' },
      { title: 'Matemáticas', duration: '8 min' },
      { title: 'Ciencias', duration: '8 min' },
      { title: 'Lecciones', duration: '10 min' },
      { title: 'Ejercicios', duration: '10 min' },
      { title: 'Pruebas', duration: '10 min' },
      { title: 'Configurar cuenta', duration: '10 min' },
      { title: 'Compartir cuenta', duration: '8 min' },
      { title: 'Importar cuenta', duration: '8 min' },
      { title: 'Exportar cuenta', duration: '8 min' },
      { title: 'Guardar cuenta', duration: '7 min' },
      { title: 'Administrar cuenta', duration: '8 min' },
      { title: 'Eliminarlas', duration: '5 min' },
      { title: 'Copiarlas', duration: '5 min' },
      { title: 'Descargarlas', duration: '5 min' },
      { title: 'Iniciar', duration: '5 min' },
      { title: 'Iniciar sesiones', duration: '8 min' },
      { title: 'Seleccionar sesiones', duration: '5 min' },
      { title: 'Métodos de entrega', duration: '8 min' },
      { title: 'Ajustes de inicio de sesión', duration: '8 min' },
      { title: 'Carrera espacial', duration: '8 min' },
      { title: 'Elegir sesiones', duration: '5 min' },
      { title: 'Configurar equipos', duration: '8 min' },
      { title: 'Elegir ajustes', duration: '8 min' },
      { title: 'Pregunta final', duration: '5 min' },
      { title: 'Resultados', duration: '10 min' },
      { title: 'Compartir resultados', duration: '8 min' },
      { title: 'Exportar resultados', duration: '8 min' },
      { title: 'Informes', duration: '10 min' },
      { title: 'Buscar informes', duration: '8 min' },
      { title: 'Filtrar informes', duration: '8 min' },
      { title: 'Archivar informes', duration: '8 min' },
      { title: 'Eliminar informes', duration: '8 min' },
      { title: 'Configurar perfil', duration: '7 min' },
    ]
  },
  'wix': {
    title: 'Wix: Website Builder',
    description: 'Learn how to use Wix for effective website building and online presence.',
    instructor: 'Laura Davis',
    instructorBio: 'Digital project manager with experience in agile methodologies.',
    instructorImage: 'https://randomuser.me/api/portraits/women/77.jpg',
    rating: 4.8,
    students: 140,
    duration: '2 hours',
    level: 'Intermediate',
    badge: '/assets/courses/badges/intermediate.png',
    lessons: [
      { title: '¿Qué es Wix?', duration: '5 min', completed: true },
      { title: 'Primeros pasos', duration: '8 min', completed: true },
      { title: 'Crear cuenta', duration: '7 min', completed: true },
      { title: 'Iniciar sesión', duration: '5 min' },
      { title: 'Conocer el menú', duration: '10 min' },
      { title: 'Clases', duration: '10 min' },
      { title: 'Cambiar nombre', duration: '5 min' },
      { title: 'Compartir clase', duration: '5 min' },
      { title: 'Inicio', duration: '5 min' },
      { title: 'Sitios web', duration: '8 min' },
      { title: 'Crear sitio web', duration: '10 min' },
      { title: 'Editar sitio web', duration: '10 min' },
      { title: 'Configurar sitio web', duration: '10 min' },
      { title: 'Compartir sitio web', duration: '8 min' },
      { title: 'Importar sitio web', duration: '8 min' },
      { title: 'Exportar sitio web', duration: '8 min' },
      { title: 'Guardar sitio web', duration: '7 min' },
      { title: 'Administrar sitios web', duration: '8 min' },
      { title: 'Eliminarlas', duration: '5 min' },
      { title: 'Copiarlas', duration: '5 min' },
      { title: 'Descargarlas', duration: '5 min' },
      { title: 'Iniciar', duration: '5 min' },
      { title: 'Iniciar sesiones', duration: '8 min' },
      { title: 'Seleccionar sesiones', duration: '5 min' },
      { title: 'Métodos de entrega', duration: '8 min' },
      { title: 'Ajustes de inicio de sesión', duration: '8 min' },
      { title: 'Carrera espacial', duration: '8 min' },
      { title: 'Elegir sesiones', duration: '5 min' },
      { title: 'Configurar equipos', duration: '8 min' },
      { title: 'Elegir ajustes', duration: '8 min' },
      { title: 'Pregunta final', duration: '5 min' },
      { title: 'Resultados', duration: '10 min' },
      { title: 'Compartir resultados', duration: '8 min' },
      { title: 'Exportar resultados', duration: '8 min' },
      { title: 'Informes', duration: '10 min' },
      { title: 'Buscar informes', duration: '8 min' },
      { title: 'Filtrar informes', duration: '8 min' },
      { title: 'Archivar informes', duration: '8 min' },
      { title: 'Eliminar informes', duration: '8 min' },
      { title: 'Configurar perfil', duration: '7 min' },
    ]
  },
  'wordpress': {
    title: 'WordPress: Blogging and CMS',
    description: 'Learn how to use WordPress for effective blogging and content management system.',
    instructor: 'David Rodriguez',
    instructorBio: 'Digital communication specialist with experience in digital transformation.',
    instructorImage: 'https://randomuser.me/api/portraits/men/88.jpg',
    rating: 4.7,
    students: 160,
    duration: '2.5 hours',
    level: 'Intermediate',
    badge: '/assets/courses/badges/intermediate.png',
    lessons: [
      { title: '¿Qué es WordPress?', duration: '5 min', completed: true },
      { title: 'Primeros pasos', duration: '8 min', completed: true },
      { title: 'Crear cuenta', duration: '7 min', completed: true },
      { title: 'Iniciar sesión', duration: '5 min' },
      { title: 'Conocer el menú', duration: '10 min' },
      { title: 'Clases', duration: '10 min' },
      { title: 'Cambiar nombre', duration: '5 min' },
      { title: 'Compartir clase', duration: '5 min' },
      { title: 'Inicio', duration: '5 min' },
      { title: 'Blogs', duration: '8 min' },
      { title: 'Crear blog', duration: '10 min' },
      { title: 'Editar blog', duration: '10 min' },
      { title: 'Configurar blog', duration: '10 min' },
      { title: 'Compartir blog', duration: '8 min' },
      { title: 'Importar blog', duration: '8 min' },
      { title: 'Exportar blog', duration: '8 min' },
      { title: 'Guardar blog', duration: '7 min' },
      { title: 'Administrar blogs', duration: '8 min' },
      { title: 'Eliminarlas', duration: '5 min' },
      { title: 'Copiarlas', duration: '5 min' },
      { title: 'Descargarlas', duration: '5 min' },
      { title: 'Iniciar', duration: '5 min' },
      { title: 'Iniciar sesiones', duration: '8 min' },
      { title: 'Seleccionar sesiones', duration: '5 min' },
      { title: 'Métodos de entrega', duration: '8 min' },
      { title: 'Ajustes de inicio de sesión', duration: '8 min' },
      { title: 'Carrera espacial', duration: '8 min' },
      { title: 'Elegir sesiones', duration: '5 min' },
      { title: 'Configurar equipos', duration: '8 min' },
      { title: 'Elegir ajustes', duration: '8 min' },
      { title: 'Pregunta final', duration: '5 min' },
      { title: 'Resultados', duration: '10 min' },
      { title: 'Compartir resultados', duration: '8 min' },
      { title: 'Exportar resultados', duration: '8 min' },
      { title: 'Informes', duration: '10 min' },
      { title: 'Buscar informes', duration: '8 min' },
      { title: 'Filtrar informes', duration: '8 min' },
      { title: 'Archivar informes', duration: '8 min' },
      { title: 'Eliminar informes', duration: '8 min' },
      { title: 'Configurar perfil', duration: '7 min' },
    ]
  },
  'shopify': {
    title: 'Shopify: E-commerce',
    description: 'Learn how to use Shopify for effective e-commerce website building and online sales.',
    instructor: 'Emma Thompson',
    instructorBio: 'Digital freelancer with experience in digital marketing and web development.',
    instructorImage: 'https://randomuser.me/api/portraits/women/22.jpg',
    rating: 4.7,
    students: 190,
    duration: '2.5 hours',
    level: 'Intermediate',
    badge: '/assets/courses/badges/intermediate.png',
    lessons: [
      { title: '¿Qué es Shopify?', duration: '5 min', completed: true },
      { title: 'Primeros pasos', duration: '8 min', completed: true },
      { title: 'Crear cuenta', duration: '7 min', completed: true },
      { title: 'Iniciar sesión', duration: '5 min' },
      { title: 'Conocer el menú', duration: '10 min' },
      { title: 'Clases', duration: '10 min' },
      { title: 'Cambiar nombre', duration: '5 min' },
      { title: 'Compartir clase', duration: '5 min' },
      { title: 'Inicio', duration: '5 min' },
      { title: 'Tiendas', duration: '8 min' },
      { title: 'Crear tienda', duration: '10 min' },
      { title: 'Editar tienda', duration: '10 min' },
      { title: 'Configurar tienda', duration: '10 min' },
      { title: 'Compartir tienda', duration: '8 min' },
      { title: 'Importar tienda', duration: '8 min' },
      { title: 'Exportar tienda', duration: '8 min' },
      { title: 'Guardar tienda', duration: '7 min' },
      { title: 'Administrar tiendas', duration: '8 min' },
      { title: 'Eliminarlas', duration: '5 min' },
      { title: 'Copiarlas', duration: '5 min' },
      { title: 'Descargarlas', duration: '5 min' },
      { title: 'Iniciar', duration: '5 min' },
      { title: 'Iniciar sesiones', duration: '8 min' },
      { title: 'Seleccionar sesiones', duration: '5 min' },
      { title: 'Métodos de entrega', duration: '8 min' },
      { title: 'Ajustes de inicio de sesión', duration: '8 min' },
      { title: 'Carrera espacial', duration: '8 min' },
      { title: 'Elegir sesiones', duration: '5 min' },
      { title: 'Configurar equipos', duration: '8 min' },
      { title: 'Elegir ajustes', duration: '8 min' },
      { title: 'Pregunta final', duration: '5 min' },
      { title: 'Resultados', duration: '10 min' },
      { title: 'Compartir resultados', duration: '8 min' },
      { title: 'Exportar resultados', duration: '8 min' },
      { title: 'Informes', duration: '10 min' },
      { title: 'Buscar informes', duration: '8 min' },
      { title: 'Filtrar informes', duration: '8 min' },
      { title: 'Archivar informes', duration: '8 min' },
      { title: 'Eliminar informes', duration: '8 min' },
      { title: 'Configurar perfil', duration: '7 min' },
    ]
  },
};

const courseDataWithAliases: Record<string, CourseDetail> = {
  ...courseData,
  'course-1': courseData['wayground'],
  'course-2': courseData['socrative'],
  'course-3': courseData['brainscape'],
  'course-4': courseData['genially'],
  'course-5': courseData['visme'],
  'course-6': courseData['canva'],
  'course-7': courseData['adobe-express'],
  'course-8': courseData['canvas'],
  'course-9': courseData['google-classroom'],
  'course-10': courseData['google-docs'],
  'course-11': courseData['google-suite'],
  'course-12': courseData['powtoon'],
  'course-13': courseData['moovly'],
  'course-14': courseData['duolingo'],
  'course-15': courseData['google-scholar'],
  'course-16': courseData['khan-academy'],
};

export default function CourseDetail() {
  const { id } = useParams();
  const course = id ? courseDataWithAliases[id] : undefined;

  if (!course) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-gray-900 mb-4">Course not found</h1>
          <p className="text-gray-600">The course you're looking for doesn't exist.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 py-12">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Main Content */}
          <div className="lg:col-span-2 space-y-6">
            {/* Course Header */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
            >
              <h1 className="text-4xl font-decorative font-bold text-gray-900 mb-4">{course.title}</h1>
              <p className="text-xl text-gray-600 mb-6">{course.description}</p>
              
              <div className="flex items-center gap-6 text-sm text-gray-500 mb-6">
                <div className="flex items-center gap-1">
                  <Star className="h-4 w-4 fill-yellow-400 text-yellow-400" />
                  <span>{course.rating}</span>
                </div>
                <div className="flex items-center gap-1">
                  <Users className="h-4 w-4" />
                  <span>{course.students} students enrolled</span>
                </div>
                <div className="flex items-center gap-1">
                  <Clock className="h-4 w-4" />
                  <span>{course.duration}</span>
                </div>
                <span className="bg-secondary/10 text-secondary px-2 py-1 rounded-full text-xs">
                  {course.level}
                </span>
                {course.badge && <img src={course.badge} alt={course.level + ' badge'} className="inline-block h-6 ml-2 align-middle" />}
              </div>
            </motion.div>

            {/* Video Section */}
            {course.video && (
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8, delay: 0.1 }}
              >
      <Card>
        <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                      <Play className="h-5 w-5" />
                      Course Preview
                    </CardTitle>
        </CardHeader>
        <CardContent>
            <div className="aspect-video w-full rounded-lg overflow-hidden shadow">
              <iframe
                src={course.video}
                title={course.title}
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
                className="w-full h-full border-none"
              />
            </div>
                  </CardContent>
                </Card>
              </motion.div>
            )}

            {/* Course Content */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 0.2 }}
            >
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <BookOpen className="h-5 w-5" />
                    Course Content
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    {course.lessons.map((lesson: { title: string; duration: string; completed?: boolean }, index: number) => (
                      <div key={index} className="flex items-center justify-between p-3 border rounded-lg">
                        <div className="flex items-center gap-3">
                          {lesson.completed ? (
                            <CheckCircle className="h-5 w-5 text-green-500" />
                          ) : (
                            <div className="h-5 w-5 rounded-full border-2 border-gray-300" />
                          )}
                          <span className="font-medium">{lesson.title}</span>
                        </div>
                        <span className="text-sm text-gray-500">{lesson.duration}</span>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          </div>

          {/* Sidebar */}
          <div className="space-y-6">
            {/* Enroll Card */}
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8, delay: 0.3 }}
            >
              <Card className="sticky top-6">
                <CardContent className="p-6">
                  <div className="text-center mb-6">
                    <h3 className="text-2xl font-bold text-gray-900 mb-2">Free Course</h3>
                    <p className="text-gray-600">No payment required</p>
                  </div>
                  
                  <Button className="w-full bg-secondary hover:bg-secondary/90 text-white text-lg py-3 mb-4">
                    Enroll for Free
                  </Button>
                  
                  <div className="space-y-3 text-sm">
                    <div className="flex items-center gap-2">
                      <CheckCircle className="h-4 w-4 text-green-500" />
                      <span>Full lifetime access</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <CheckCircle className="h-4 w-4 text-green-500" />
                      <span>Access on mobile and TV</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <CheckCircle className="h-4 w-4 text-green-500" />
                      <span>Certificate of completion</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <CheckCircle className="h-4 w-4 text-green-500" />
                      <span>30-Day money-back guarantee</span>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </motion.div>

            {/* Instructor Card */}
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.8, delay: 0.4 }}
            >
              <Card>
                <CardHeader>
                  <CardTitle>Instructor</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center gap-4 mb-4">
                    <img 
                      src={course.instructorImage} 
                      alt={course.instructor} 
                      className="w-16 h-16 rounded-full object-cover"
                    />
                    <div>
                      <h3 className="font-semibold text-gray-900">{course.instructor}</h3>
                      <p className="text-sm text-gray-500">Course Instructor</p>
                    </div>
                  </div>
                  <p className="text-sm text-gray-600">{course.instructorBio}</p>
        </CardContent>
      </Card>
            </motion.div>
          </div>
        </div>
      </div>
    </div>
  );
} 